using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class StaticImageAnimationHelper : MonoBehaviour
{
    public Image uiImageHolder;
    public List<Sprite> sprites = new List<Sprite>();
    public float frameTime;

    private int _currentFrame;
    private TimerHelper _frameTimer;

    // Start is called before the first frame update
    void Start()
    {
        _currentFrame = 0;
        _frameTimer = new TimerHelper(frameTime);
    }

    // Update is called once per frame
    void Update()
    {
        if (uiImageHolder != null)
        {
            if (_frameTimer.HasTicked(Time.deltaTime))
            {
                uiImageHolder.sprite = sprites[_frameTimer.TimesRun % sprites.Count];                
            }
        }
    }
}
