using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GoTextFadeHelper : MonoBehaviour
{
    private bool _nowActive = false;
    public float fadeTime;
    private TimerHelper _fadeTimer;

    public AudioSource sfxAudioSource;
    public AudioClip startAudioClip;

    // Start is called before the first frame update
    void Start()
    {
        _fadeTimer = new TimerHelper(fadeTime, false);        
    }

    public void StartFade()
    {
        _nowActive = true;
        if (sfxAudioSource != null && startAudioClip != null)
        {
            sfxAudioSource.clip = startAudioClip;
            sfxAudioSource.Play();
        }
    }

    // Update is called once per frame
    void Update()
    {
        if (_nowActive)
        {
            if (_fadeTimer.HasTicked(Time.deltaTime))
            {
                Destroy(gameObject);
            }
        }
    }
}
