using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraManager : MonoBehaviour
{
    public GameObject followedGO;
    private Vector3 _followOffset;

    // Start is called before the first frame update
    void Start()
    {
        _followOffset = transform.position - followedGO.transform.position;
    }

    // Update is called once per frame
    void LateUpdate()
    {
        transform.position = followedGO.transform.position + _followOffset;
    }
}
