using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShieldPowerUpColliderManager : ColliderManager
{
    public float immunityLength;
    public AudioClip tokenPickupSFX;
    private AudioSource _audioSource;
    private GameObject _player;

    // Bool checks if the core has been collected, this is because the ships are made of multiple collision boxes and would trigger more than once.
    private bool _tokenCollected = false;

    public override void DoAwakeTasks()
    {
        _player = GameObject.Find("Player");
        _audioSource = _player.GetComponent<AudioSource>();
        base.DoAwakeTasks();
    }

    public override void ProcessCollision(CollisionDirection direction, Collision collision, bool wasChild)
    {
        GameObject collisionGO;
        if (wasChild)
        {
            collisionGO = collision.transform.parent.gameObject;
        }
        else
        {
            collisionGO = collision.gameObject;
        }

        // Check the tag of the collided object, Direction doesnt matter i assume
        switch (collisionGO.tag)
        {
            case "Player":
                PickupToken();
                break;
        }

    }

    /// <summary>
    /// Process the core pick up and destroy the core object.
    /// </summary>
    public void PickupToken()
    {
        // If the core has been collected ignore it.
        if (!_tokenCollected)
        {
            _tokenCollected = true;
            if (_audioSource != null)
            {
                _audioSource.PlayOneShot(tokenPickupSFX);
            }
            if (_player != null)
            {
                PlayerColliderManager currentPCM = _player.GetComponent<PlayerColliderManager>();
                if (currentPCM != null)
                {
                    currentPCM.SetImmune(immunityLength);
                }
            }
            
            if (transform.childCount > 0)
            {
                for (int i = 0; i < transform.childCount; i++)
                {
                    transform.GetChild(i).gameObject.SetActive(false);
                }
            }

            Destroy(gameObject, 2.0f);
        }
    }
}
